name: build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: git ref to checkout

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
            "x86_64-unknown-linux-gnu",
            # "x86_64-pc-windows-msvc",
            "x86_64-apple-darwin",
            "aarch64-apple-darwin",
            "aarch64-linux-android",
          ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}

      - name: cargo build
        run: |
          cargo build --release
          mv ./target/release/dragalia-cdn ./dragalia-cdn-${{ matrix.target }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./dragalia-cdn-${{ matrix.target }}

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-pc-windows-msvc

      - name: cargo build
        run: |
          cargo build --release
          mv .\target\release\dragalia-cdn.exe .\dragalia-cdn-x86_64-pc-windows-msvc.exe

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-pc-windows-msvc
          path: .\dragalia-cdn-x86_64-pc-windows-msvc.exe
